# Setup
title:        Octopy
tagline:      A Multiprocessing Federated Learning Simulation Tool
tagline2:     Team 13 Meng Dong, Xin Dong, Danyun He, Ziao Lin
baseurl:      "/"
paginate:     1
locale:       "en"

# About/contact
author:
  name:       Meng Dong, Xin Dong, Danyun He, Ziao Lin
  url:        http://yourhomepage.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
